# -*- mode: ruby -*-
Vagrant.configure(2) do |config|
  config.vm.box = "ubuntu/xenial64"
  config.vm.box_version = "20171201.0.0"
  config.vm.box_check_update = false
  config.vm.network "forwarded_port", guest: 22, host: 2222
  config.vm.network "forwarded_port", guest: 8080, host: 8080
  config.vm.provider "virtualbox" do |v|
    v.gui = false
    v.name = "myvm"
    v.memory = 4096
  end
  config.vm.provision "shell" do |s|
    s.inline = "echo 'ubuntu:123' | sudo chpasswd"
  end
end
